**Python DA Assignment 1: Data Analysis using NumPy and Pandas**

**Numpy Array Operations:**

In [2]:
import numpy as np

In [22]:
# 1creating 1D numpy array
temperature_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperature_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [24]:
# 2. Inspection and Properties:
print("Shape of the temperature_w1: ",temperature_w1.shape)
print("Data type of the temperature_w1: ",temperature_w1.dtype)
print("Number of Elements of the temperature_w1: ",temperature_w1.size)

Shape of the temperature_w1:  (7,)
Data type of the temperature_w1:  float64
Number of Elements of the temperature_w1:  7

In [29]:
# 3. Array Operations:
temp_w1_f = (temperature_w1 * 9/5) + 32
print("Week 1 tmparature in Fahrenheit",temp_w1_f)
print("Max Temparature: ",np.max(temp_w1_f))
print("Min Temparature: ",np.min(temp_w1_f))
print("Mean Temparature: ",np.mean(temp_w1_f))

Week 1 tmparature in Fahrenheit [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Max Temparature:  78.98
Min Temparature:  69.44
Mean Temparature:  74.37714285714286

In [30]:
# 4. Array Slicing and Indexing

print("First 3 days:", temperature_w1[:3])
print("Weekend (last 2 days):", temperature_w1[-2:])
print("Middle 3 days (days 3 to 5):", temperature_w1[2:5])

First 3 days: [22.5 25.3 20.8]
Weekend (last 2 days): [24.8 21.9]
Middle 3 days (days 3 to 5): [20.8 23.4 26.1]

In [37]:
# 5. Create a 2D Array
temperatures =np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("2D array : ",temperatures)

2D array :  [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [38]:
#6. Inspect and Slice the 2D Array:

print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Elements:", temperatures.size)

Shape: (2, 7)
Data Type: float64
Total Elements: 14

In [59]:
#Week and Week End wise temperature
print("week 1 temparature :", temperatures[0, :])
print("week 1 > weekend temparature :",temperatures[0,-2:])
print("week 2 temparature :", temperatures[1, : ])
print("week 2 > weekend temparature :",temperatures[1,-2:])

week 1 temparature : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
week 1 > weekend temparature : [24.8 21.9]
week 2 temparature : [19.2 22.5 21.3 24.  23.5 22.8 20.1]
week 2 > weekend temparature : [22.8 20.1]

**Pandas Series:**

In [62]:
# 1. Creating Pandas Series:
import pandas as pd

marks_data = [95, 92, 89, 85, 80]
indices = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
marks = pd.Series(data=marks_data, index=indices)
print("Original Marks Series: ", marks)

Original Marks Series:  Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [71]:
# 2. Indexing and Slicing:
print("Mark of the first rank student: ",marks.iloc[0])
print("Mark of the top 3 Ranks: ",marks.loc[['Rank1','Rank2','Rank3']])
print("Mark of the 3rd Rank ",marks.iloc[2])

mask = marks > 90
print("Ranks with Marks > 90: ",marks[mask])

Mark of the first rank student:  95
Mark of the top 3 Ranks:  Rank1    95
Rank2    92
Rank3    89
dtype: int64
Mark of the 3rd Rank  89
Ranks with Marks > 90:  Rank1    95
Rank2    92
dtype: int64

In [89]:
# 3. Manipulating Series:

#serirs can be updated like dictories so,
marks["Rank1"] = 100
print("\n Updated Marks Series: ")
print(marks)


#an entry can be removed  using .drop()
#marks = marks.drop('Rank5')
print("\n Rank5  removed data")
print("\n",marks)

 Updated Marks Series:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

 Rank5  removed data

 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [95]:
# CGPA
cgpa = marks/10
print("CGPA:\n",cgpa)

CGPA:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

**Pandas DataFrame:**

In [96]:
# 1. Creating Pandas DataFrame
import pandas as pd

data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West',
               'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}
transactions = pd.DataFrame(data)
print("Transactions DataFrame:\n", transactions)

Transactions DataFrame:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [104]:
# 2. Data Exploration:
print("Transaction Head \n",transactions.head())
print("Transaction Tail \n",transactions.tail())
print("Transaction Shape\n",transactions.shape)
print("Transaction Columns\n",transactions.columns)
print("Transaction Data Type\n",transactions.dtypes)

Transaction Head
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
Transaction Tail
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
Transaction Shape
 (10, 4)
Transaction Columns
 Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
Transaction Data Type
 TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [105]:
#Product Category and Amount Column
transactions[['ProductCategory','Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [119]:
#last 3 columns of the dataframe
transactions.iloc[:,-3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [124]:
#filter region Nort and Amount >200
filtered_transactions = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print(filtered_transactions)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [125]:
#value count for product category
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [126]:
#Unique values in Region colums
transactions['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [127]:
#Mean amount by Region
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [130]:
# 3. Manipulating the DataFrame:

#Amount modifaction for transcation id 102
transactions.loc[transactions['TransactionID']==102,'Amount'] =165
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [131]:
#Creating new colum Discount by caclualting 10% of amount
transactions['Discount'] = transactions['Amount'] *.10
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [134]:
#Removing row with trasaction id 109
transactions = transactions.drop(transactions[transactions['TransactionID']== 109] .index)
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [138]:
#deleting the discount column from the DataFrame
transactions= transactions.drop(columns =['Discount'])
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400